#!/bin/sh


user=$(whoami)
nl=$(cat /etc/crontab | grep -c 'finalattendance')
if [ "$nl" -eq 0 ]
then
	echo "0  9  * * * $user finalattendance" | tee -a /etc/crontab >/dev/null 2>&1
fi

touch ~ChiefCommander/attendance_report.txt

Date=$(date -I -d "-1 day")

grep -i "$Date.* Army" attendance.log | awk '{print "\t"substr($1,2,10),$2,$3}' | tee -a ~ArmyGeneral/attendance_record.txt
grep -i "$Date.* Navy" attendance.log | awk '{print "\t"substr($1,2,10),$2,$3}' | tee -a ~NavyMarshal/attendance_record.txt
grep -i "$Date.* AirForce" attendance.log | awk '{print "\t"substr($1,2,10),$2,$3}' | tee -a ~AirForceChief/attendance_record.txt

	
